### ISSUE TITLE
Version 1.0.0 - Stable

### ISSUE THREAD

**Issue by SamBrishes** [SamBrishes/wolfcms-wordpress-admintheme#2]
The next version of the WordPress 3.8 AdminTheme will (maybe) released for the next major Wolf CMS Update. And here you will find all incoming changes and features (+ status):

* [ ] 4 New Color Schemes
 * [ ] Frog Color Scheme
 * [ ] Wolf Color Scheme
 * [ ] Fox Color Scheme
 * [ ] pytesNET Color Scheme
* [ ] Responsive Design
* [ ] Better Menu-Tab Badge Design
* [ ] Configurable Sidebar Width

## Maybe's
* [ ] Support for Opera Browser 11+
* [ ] Support for Mozilla Firefox 5+
* [ ] Support for Internet Explorer 8+

## Do you have any wishes?
Let me know. Write me your desires right here. :D

**Comment by dajare** [comment]
Looks great! (Typo alert: "Color S**c**hemes"! + "Badge**t**?)

**Comment by SamBrishes** [comment]
Oops, Thank you! ^^
